// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7pVXaqQ3BFIWpfDXZ-q1SO7_lzCaeL58',
    appId: '1:767574809824:android:4a757a3c2418ad339e8485',
    messagingSenderId: '767574809824',
    projectId: 'coding-chatting-yjh',
    databaseURL: 'https://coding-chatting-yjh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coding-chatting-yjh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOGc9ru9unpEaVqs2PwTIvqb4OLAp0gV0',
    appId: '1:767574809824:ios:f49dccb1e263ecad9e8485',
    messagingSenderId: '767574809824',
    projectId: 'coding-chatting-yjh',
    databaseURL: 'https://coding-chatting-yjh-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'coding-chatting-yjh.appspot.com',
    iosClientId: '767574809824-qfuqp68f4lb2d60iarnqmmnbfjtoekgn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyf',
  );
}
